module Problem45

(*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*)
let tri n = (n*(n+1))/2
let tris = Seq.initInfinite tri

let pent n = (n*(3*n - 1))/2
let pents = Seq.initInfinite pent
//cf. Problem 44
let inversePent (v : int) = 
    (1.0/6.0) + sqrt ((2.0/3.0)*(float v) + (1.0/36.0))

let hex n = n*(2*n - 1)
let hexs = Seq.initInfinite
let inverseHex (v : int) = 
    (0.25) + sqrt (0.5*(float v) + 0.0625)
