using System;
using System.Collections.Generic;
using System.Text;

namespace CSharpSolutions.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    ///1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    ///Solution: 4613732
    /// </summary>
    public class Problem2
    {
        private const int FourMillion = 4 * 1000000;

        private static int SumEvenFibs (int f1, int f2, int sum)
        {
            if (f2 < FourMillion)
            {
                if (f2 % 2 == 0)
                    sum += f2;

                return SumEvenFibs(f2, f1 + f2, sum);
            }

            return sum;
        }

        public static string Solve()
        {
            return SumEvenFibs(1, 2, 0).ToString();
        }
    }
}
